services:
  web:
    build: .
    volumes:
      - static_volume:/app/static
    env_file:
      - ./.env.prod
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/static
    env_file:
      - ./.env.prod
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
