# Generated by Django 5.2.3 on 2025-06-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image_path",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
