# Generated by Django 5.2.3 on 2025-06-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
